### ISSUE TITLE
Linebreak on any page

### ISSUE THREAD

**Issue by pfrechFra** [antonroesler/softDsim#147]
There is a small problem with the wordbreak, especially on the help page.

**Comment by antonroesler** [comment]
more specific please. Can you provide examples, sceenshots?

**Comment by pfrechFra** [comment]
sure, screenshot explains this the best way 
![Bildschirmfoto 2022-05-10 um 09 54 59](https://user-images.githubusercontent.com/64014742/167578095-241751d2-b781-426e-9c6e-1da60479b964.png)
